export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const CREATE_CAFE = "CREATE_CAFE";
export const CAFE_LIST = "CAFE_LIST";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const EMPLOYEE_LIST = "EMPLOYEE_LIST";
